const staticDemo=true;
let token=null,state=null,busy=false;
let widgetSettings;try{widgetSettings=JSON.parse(localStorage.getItem('orbit.widget')||'null')}catch{}
const sampleTrips={
 'sample-maya':{name:'Maya',stops:[{zone:'Europe/London',lat:51.5074,lon:-.1278},{zone:'Asia/Dubai',lat:25.2048,lon:55.2708},{zone:'Asia/Tokyo',lat:35.6762,lon:139.6503}]},
 'sample-leo':{name:'Leo',stops:[{zone:'America/New_York',lat:40.7128,lon:-74.006},{zone:'America/Los_Angeles',lat:34.0522,lon:-118.2437},{zone:'Pacific/Honolulu',lat:21.3099,lon:-157.8581}]},
 'sample-aiko':{name:'Aiko',stops:[{zone:'Asia/Tokyo',lat:35.6762,lon:139.6503},{zone:'Asia/Singapore',lat:1.3521,lon:103.8198},{zone:'Australia/Sydney',lat:-33.8688,lon:151.2093}]}
};
// Recover safely from old or damaged device preferences.
if(!widgetSettings||typeof widgetSettings!=='object'||Array.isArray(widgetSettings))widgetSettings={};
const validZone=z=>{try{if(typeof z!=='string')return false;new Intl.DateTimeFormat(undefined,{timeZone:z});return true}catch{return false}};
widgetSettings.zones=Array.isArray(widgetSettings.zones)?[...new Set(widgetSettings.zones.filter(validZone))]:[];
widgetSettings.friends=Array.isArray(widgetSettings.friends)?widgetSettings.friends.filter(x=>typeof x==='string'):null;
widgetSettings.order=Array.isArray(widgetSettings.order)?widgetSettings.order.filter(x=>typeof x==='string'):[];
widgetSettings.excludedSamples=Array.isArray(widgetSettings.excludedSamples)?widgetSettings.excludedSamples.filter(x=>typeof x==='string'):[];
widgetSettings.size=['small','medium','large'].includes(widgetSettings.size)?widgetSettings.size:'medium';
widgetSettings.style=['analog','digital'].includes(widgetSettings.style)?widgetSettings.style:'digital';
widgetSettings.sample=widgetSettings.sample===true;
widgetSettings.demoStep=Number.isSafeInteger(widgetSettings.demoStep)&&widgetSettings.demoStep>=0?widgetSettings.demoStep:0;
function saveWidget(){localStorage.setItem('orbit.widget',JSON.stringify(widgetSettings));renderWidget();renderClockOrder();if(typeof renderDashboard==='function')renderDashboard()}
function widgetClocks(){const friends=[...(state?.friends||[]),...(widgetSettings.sample?sampleWidgetPeople():[])].filter(f=>f.sample||widgetSettings.friends===null||widgetSettings.friends.includes(f.id));const clocks=[...friends,...widgetSettings.zones.map(z=>({id:'zone:'+z,name:z.split('/').pop().replaceAll('_',' '),zone:z,standalone:true}))];const order=widgetSettings.order||[];return clocks.sort((a,b)=>{const rank=id=>{const i=order.indexOf(id);return i<0?order.length:i};return rank(a.id)-rank(b.id)})}
function renderWidget(){const clocks=widgetClocks();$('widgetFrame').className='widget '+widgetSettings.size+' '+(widgetSettings.style||'digital');$('clockStyle').value=widgetSettings.style||'digital';$('samplePeople').checked=!!widgetSettings.sample;$('widgetFrame').querySelector('.widgetTitle').innerHTML='◉ orbit <span>'+(widgetSettings.sample?'SAMPLE PEOPLE':'YOUR PEOPLE')+'</span>';document.querySelectorAll('[data-size]').forEach(b=>b.classList.toggle('active',b.dataset.size===widgetSettings.size));$('widgetRows').innerHTML=clocks.slice(0,{small:1,medium:3,large:6}[widgetSettings.size]).map(f=>`<div class="widgetRow"><div>${escape(f.name)}<small>${f.sample?'Sample · '+f.zone.split('/').pop().replaceAll('_',' '):f.standalone?'Time zone clock':age(f.updated)}</small><span class="zoneDelta" title="Compared with your time zone">${OrbitClock.signedDifferenceAt(f.zone,zone())}</span></div><div class="clockDisplay">${widgetSettings.style==='analog'?analogFace(f.zone):'<strong>'+time(f.zone)+'</strong>'}</div></div>`).join('')||'<p class="muted">Choose a friend or add a time zone.</p>';}
function renderWidgetSettings(){renderWidget();renderClockOrder();const available=(state?.friends||[]).filter(f=>widgetSettings.friends!==null&&!widgetSettings.friends.includes(f.id));$('friendToAdd').innerHTML=available.map(f=>`<option value="${escape(f.id)}">${escape(f.name)}</option>`).join('');$('friendToAdd').parentElement.hidden=!available.length;if(typeof renderDashboard==='function')renderDashboard()}


const $=id=>document.getElementById(id);
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const zone=()=>Intl.DateTimeFormat().resolvedOptions().timeZone;
async function api(path,data){throw Error('Live accounts and sharing need the Orbit tracking server. This public site is a demo.');const r=await fetch('/api/'+path,{method:data?'POST':'GET',headers:{'Content-Type':'application/json',Authorization:'Bearer '+(token||'')},body:data?JSON.stringify(data):undefined});const b=await r.json();if(!r.ok)throw Error(b.error||'Request failed');return b}
function note(s){$('status').textContent=s}
function time(z){return OrbitClock.timeAt(z)}
function age(t){const m=Math.max(0,Math.floor((Date.now()/1000-t)/60));return m>=15?`Last seen ${m<60?m+'m':Math.floor(m/60)+'h'} ago · may be outdated`:m<1?'Updated just now':m<60?`Updated ${m}m ago`:`Updated ${Math.floor(m/60)}h ago`}
function diff(z){return OrbitClock.differenceAt(z,zone())}
function render(){ $('localClock').textContent=time(zone());$('localZone').textContent=zone().replaceAll('_',' ');if(!state)$('syncLabel').textContent='Clocks run on this device';
$('empty').hidden=displayPeople().length>0;
$('cards').innerHTML=displayPeople().map(f=>`<article class="card"><div class="person"><div class="avatar">${escape(f.name.slice(0,1).toUpperCase())}</div><div><h3>${escape(f.name)}</h3><small>${f.sample?'Sample · ':''}${escape(f.zone.split('/').pop().replaceAll('_',' '))}</small></div></div><div class="clock">${time(f.zone)}</div><div class="day">${new Intl.DateTimeFormat(undefined,{timeZone:f.zone,weekday:'long',month:'short',day:'numeric'}).format(new Date())}</div><span class="difference">${OrbitClock.signedDifferenceAt(f.zone,zone())} · ${diff(f.zone)}</span>${f.mode==='location'&&f.lat!=null?`<a class="location" href="https://maps.apple.com/?ll=${f.lat},${f.lon}" target="_blank" rel="noopener">View shared location ↗ · ${f.locationUpdated?age(f.locationUpdated):'Update time unavailable'}</a>`:''}<div class="cardBottom"><span>${f.sample?'Simulated location':f.mode==='location'?'Location shared':'Time zone only'}</span><span>${age(f.updated)}</span></div></article>`).join('');
$('sharingRows').innerHTML=state?.sharing?.length?state.sharing.map(f=>`<div class="shareRow"><div><b>${escape(f.name)}</b><small>${f.mode==='paused'?'Sharing is off':f.mode==='zone'?'Only your time zone is visible':'Your coordinates and time zone are visible'}</small></div><select aria-label="Sharing with ${escape(f.name)}" data-viewer="${escape(f.id)}">${[['paused','Sharing off'],['zone','Time zone only'],['location','Live location']].map(([v,l])=>`<option value="${v}" ${v===f.mode?'selected':''}>${l}</option>`).join('')}</select></div>`).join(''):'<p class="muted">Connect with someone to choose what to share.</p>';
renderWidgetSettings();
if(typeof updateHistoryControls==='function')updateHistoryControls();
$('syncLabel').textContent='Device checked '+new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});
}
async function sync(){if(!token||busy)return;busy=true;try{state=await api('state');const payload={zone:zone()};if(state.historyEnabled || state.sharing.some(f=>f.mode==='location')){try{const p=await new Promise((resolve,reject)=>navigator.geolocation.getCurrentPosition(resolve,reject,{timeout:8000,maximumAge:30000}));payload.lat=p.coords.latitude;payload.lon=p.coords.longitude}catch{note('Location unavailable. Your time zone still updates.')}}await api('sync',payload);state=await api('state');render();if(typeof refreshDashboardHistory==='function')refreshDashboardHistory();if(!$('history').hidden && !historyDemo && !journeyPlaying)loadHistory()}catch(e){note(e.message);$('syncLabel').textContent='Offline · showing last received data'}finally{busy=false}}
$('register').onsubmit=async e=>{e.preventDefault();try{const r=await api('register',{name:$('name').value,zone:zone()});token=r.token;localStorage.setItem('orbit.token',token);$('welcome').close();await sync()}catch(e){note(e.message)}};
async function invite(){if(!token){$('welcome').showModal();return;}try{const r=await api('invite',{});$('inviteCode').textContent=r.code;$('invite').showModal()}catch(e){note(e.message)}}
$('inviteButton').onclick=invite;$('emptyInvite').onclick=invite;$('closeInvite').onclick=()=>$('invite').close();$('copyInvite').onclick=async()=>{try{await navigator.clipboard.writeText($('inviteCode').textContent);$('copyInvite').textContent='Copied'}catch{note('Select the invite code and copy it manually.')}};
$('accept').onsubmit=async e=>{e.preventDefault();try{await api('accept',{code:$('code').value});$('invite').close();note('Connected. Open Sharing to choose what they can see.');await sync()}catch(e){note(e.message);alert(e.message)}};
$('sharingRows').onchange=async e=>{const viewer=e.target.dataset.viewer;if(!viewer)return;try{await api('share',{viewer,mode:e.target.value});await sync();note('Sharing preference saved.')}catch(e){note(e.message);await sync()}};
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.body.classList.toggle('dashboardView',b.dataset.tab==='dashboard');document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.panel').forEach(x=>x.hidden=x.id!==b.dataset.tab);render()});
setInterval(()=>{ $('localClock').textContent=time(zone()); document.querySelectorAll('.card .clock').forEach((el,i)=>el.textContent=time(displayPeople()[i]?.zone||zone())); updateWidgetTimes();if(typeof tickDashboard==='function')tickDashboard(); },1000);setInterval(()=>{if(!document.hidden)sync()},30000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)sync()});
const appearance=document.createElement('div');appearance.className='appearance';appearance.innerHTML='<label for="theme">Appearance</label><select id="theme"><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select>';document.querySelector('footer').prepend(appearance);
const systemTheme=matchMedia('(prefers-color-scheme: dark)');$('theme').value=(['system','light','dark'].includes(localStorage.getItem('orbit.theme'))?localStorage.getItem('orbit.theme'):'system');function applyTheme(){const choice=$('theme').value;document.documentElement.dataset.theme=choice==='system'?(systemTheme.matches?'dark':'light'):choice;localStorage.setItem('orbit.theme',choice)}$('theme').onchange=applyTheme;systemTheme.addEventListener('change',applyTheme);applyTheme();

$('zoneChoices').innerHTML=(Intl.supportedValuesOf?Intl.supportedValuesOf('timeZone'):['UTC','Asia/Tokyo','Europe/London','America/New_York']).map(z=>`<option value="${escape(z)}">`).join('');
$('addZone').onsubmit=e=>{e.preventDefault();const z=$('zoneInput').value.trim();try{new Intl.DateTimeFormat(undefined,{timeZone:z}).format();if(!widgetSettings.zones.includes(z))widgetSettings.zones.push(z);$('zoneInput').value='';saveWidget();renderWidgetSettings()}catch{note('Choose a valid time zone, such as Asia/Tokyo.')}};
document.querySelectorAll('[data-size]').forEach(b=>b.onclick=()=>{widgetSettings.size=b.dataset.size;saveWidget()});renderWidgetSettings();

$('guestButton').onclick=()=>{localStorage.setItem('orbit.guest','true');$('welcome').close();document.querySelector('[data-tab=widget]').click()};
let historyPeriod='1',historyData=null,historyDemo=false,historyRequest=0,mapBox=[0,0,1000,600];
const project=OrbitJourney.project;
let worldPaths='',journeyFraction=1,journeyPlaying=false,journeyFrame=0,journeyLastTime=0;
fetch('world-land.json').then(r=>{if(!r.ok)throw Error('Map unavailable');return r.json()}).then(data=>{
 worldPaths=data.features.map(f=>{const polys=f.geometry.type==='Polygon'?[f.geometry.coordinates]:f.geometry.coordinates;return polys.map(poly=>'<path class="land" d="'+poly.map(ring=>ring.map((p,i)=>(i?'L':'M')+project(...p).map(n=>n.toFixed(2)).join(' ')).join(' ')+'Z').join(' ')+'" fill-rule="evenodd"/>').join('')}).join('');drawHistory();
if(typeof renderDashboard==='function')renderDashboard();}).catch(()=>{$('historySummary').textContent='Map could not load. Refresh to try again.'});
function updateHistoryControls(){
 const select=$('historyPerson'),old=select.value;const choices=[...(state?[{id:state.me.id,name:'My history'}]:[]),...displayPeople().filter(f=>f.historyAllowed)];
 const newHTML=choices.map(p=>`<option value="${escape(p.id)}">${escape(p.name)}</option>`).join('');if(select.innerHTML!==newHTML){select.innerHTML=newHTML;if(choices.some(p=>p.id===old))select.value=old;historyData=null;drawHistory();if(!$('history').hidden)loadHistory()}
 $('recordHistory').checked=!!state?.historyEnabled;$('recordHistory').disabled=!state;$('deleteHistory').disabled=!state;
 document.querySelectorAll('.shareRow').forEach((row,i)=>{const p=state.sharing[i];row.querySelectorAll('.historyShare').forEach(control=>control.remove());if(p.mode==='location'){const control=document.createElement('label');control.className='clockChoice historyShare';control.innerHTML=`<input type="checkbox" data-history-viewer="${escape(p.id)}" ${p.history_shared?'checked':''}>Share recorded history`;row.append(control)}});
}
const originalSharingChange=$('sharingRows').onchange;$('sharingRows').onchange=async e=>{const viewer=e.target.dataset.historyViewer;if(!viewer)return originalSharingChange(e);try{await api('history/share',{viewer,enabled:e.target.checked});await sync();note('History sharing saved.')}catch(error){note(error.message);await sync()}};
function fitHistory(){const points=historyData?.points||[];if(!points.length){mapBox=[0,0,1000,600];return}const xy=points.map(p=>project(p.lon,p.lat));const xs=xy.map(p=>p[0]),ys=xy.map(p=>p[1]);let w=Math.max(220,Math.max(...xs)-Math.min(...xs)+20);let h=Math.max(10,Math.max(...ys)-Math.min(...ys)+20);w=Math.max(w,h*1000/600);w=Math.min(1150,w+100);h=w*600/1000;mapBox=[(Math.min(...xs)+Math.max(...xs)-w)/2,(Math.min(...ys)+Math.max(...ys)-h)/2,w,h]}
function drawHistory(){
 const points=historyData?.points||[],svg=$('historyMap');svg.setAttribute('viewBox',mapBox.join(' '));
 const labels=[['NORTH AMERICA',-105,44],['SOUTH AMERICA',-60,-18],['EUROPE',15,53],['AFRICA',20,3],['ASIA',90,43],['AUSTRALIA',135,-25]];
 svg.innerHTML='<defs><radialGradient id="oceanGlow"><stop stop-color="var(--ocean-center)"/><stop offset="1" stop-color="var(--ocean-edge)"/></radialGradient></defs><rect x="-1500" y="-1500" width="4000" height="3500" fill="url(#oceanGlow)"/>'+worldPaths+labels.map(([name,lon,lat])=>{const [x,y]=project(lon,lat);return `<text x="${x}" y="${y}" class="continentLabel" text-anchor="middle">${name}</text>`}).join('')+'<g id="journeyRoute"></g><g id="journeyDots"></g><g id="journeyTraveler"></g>';
 renderJourney();
 $('historySummary').textContent=!historyData?(!state?'Create an account to record or view shared history.':'Select a person and period.'):!points.length?'No recorded locations in this period. History begins when recording is enabled.':`${historyData.simulatedName?'SIMULATED · '+historyData.simulatedName+' · ':historyDemo?'SAMPLE JOURNEY · Fictional locations · ':''}${points.length} ${historyData.simulatedName?'daily stops · no real tracking records':'recorded days'} · ${new Date(points[0].at*1000).toLocaleDateString()} – ${new Date(points.at(-1).at*1000).toLocaleDateString()}`;
 $('historyVisits').innerHTML=points.length?`<h3>Daily stops</h3><p class="footnote">Last reported location each day. Showing the most recent ${Math.min(points.length,20)} days.</p>`+points.slice(-20).reverse().map(p=>`<div class="visit"><span>${escape(p.day||OrbitJourney.day(p))}<small>${escape(p.zone.replaceAll('_',' '))}</small></span><span>${p.lat.toFixed(4)}°, ${p.lon.toFixed(4)}°</span></div>`).join(''):'';
}
function renderJourney(){
 const points=historyData?.points||[];if(!$('journeyRoute'))return;const steps=Math.max(0,points.length-1),progress=journeyFraction*steps,completed=Math.floor(progress),part=progress-completed;
 let paths='';for(let i=0;i<steps;i++){if(i>completed||i===completed&&part===0)continue;const target=i===completed?OrbitJourney.interpolate(points[i],points[i+1],part):points[i+1];paths+=OrbitJourney.segment(points[i],target).map(pair=>`<path class="journeyLine" d="M${pair[0].join(' ')} L${pair[1].join(' ')}"/>`).join('')}
 $('journeyRoute').innerHTML=paths;
 const radius=mapBox[2]/200;
 $('journeyDots').innerHTML=points.map((p,i)=>{const [x,y]=project(p.lon,p.lat);return `<circle class="historyDot ${i<=completed?'visited':'pending'}" cx="${x}" cy="${y}" r="${radius}" data-point="${i}" tabindex="0" role="button" aria-label="Day ${i+1}: ${escape(p.day||OrbitJourney.day(p))}"><title>${escape(p.day||OrbitJourney.day(p))} · ${p.lat.toFixed(4)}, ${p.lon.toFixed(4)}</title></circle>`}).join('');
 if(points.length){const a=points[Math.min(completed,points.length-1)],b=points[Math.min(completed+1,points.length-1)];const [x,y]=project(...Object.values(OrbitJourney.interpolate(a,b,part)));$('journeyTraveler').innerHTML=`<circle class="travelerHalo" cx="${x}" cy="${y}" r="${radius*2.7}"/><circle class="traveler" cx="${x}" cy="${y}" r="${radius*1.1}"/>`;$('journeyDate').textContent=a.day||OrbitJourney.day(a)}else{$('journeyTraveler').innerHTML='';$('journeyDate').textContent='No recorded days'}
 $('journeyProgress').value=journeyFraction*100;$('journeyPlay').disabled=points.length<2;$('journeyRestart').disabled=!points.length;$('journeyProgress').disabled=points.length<2;$('journeyPlay').textContent=journeyPlaying?'Ⅱ Pause':'▶ Play journey';$('journeyPlay').setAttribute('aria-label',journeyPlaying?'Pause journey':'Play journey');
}
function pauseJourney(){journeyPlaying=false;cancelAnimationFrame(journeyFrame);journeyLastTime=0;if($('journeyRoute'))renderJourney()}
function resetJourney(){pauseJourney();journeyFraction=1}
function animateJourney(timestamp){if(!journeyPlaying)return;if(journeyLastTime){const duration=Math.max(4,Math.min(20,(historyData?.points.length||1)*1.2));journeyFraction=Math.min(1,journeyFraction+(timestamp-journeyLastTime)/1000/duration*Number($('journeySpeed').value))}journeyLastTime=timestamp;renderJourney();if(journeyFraction>=1){pauseJourney();return}journeyFrame=requestAnimationFrame(animateJourney)}
$('journeyPlay').onclick=()=>{if(journeyPlaying){pauseJourney();return}if(journeyFraction>=1)journeyFraction=0;journeyPlaying=true;journeyLastTime=0;journeyFrame=requestAnimationFrame(animateJourney);renderJourney()};
$('journeyRestart').onclick=()=>{pauseJourney();journeyFraction=0;renderJourney()};$('journeyProgress').oninput=e=>{const fraction=Number(e.target.value)/100;pauseJourney();journeyFraction=fraction;renderJourney()};
document.addEventListener('visibilitychange',()=>{if(document.hidden)pauseJourney()});document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.tab!=='history')pauseJourney()}));
async function loadHistory(){resetJourney();if(historyDemo){showSampleHistory();return}const n=++historyRequest;historyData=null;drawHistory();if($('historyPerson').value.startsWith('sample-')){loadSamplePersonHistory($('historyPerson').value);return}if(!token||!$('historyPerson').value)return;$('historySummary').textContent='Loading recorded locations…';try{const data=await api(`history?owner=${encodeURIComponent($('historyPerson').value)}&period=${historyPeriod}&granularity=day`);if(n!==historyRequest)return;historyData=data;fitHistory();drawHistory()}catch(error){if(n===historyRequest){historyData=null;drawHistory();$('historySummary').textContent=error.message}}}
$('historyPerson').onchange=()=>{historyDemo=false;$('sampleHistory').textContent='Preview a sample journey';loadHistory()};document.querySelector('[data-tab=history]').addEventListener('click',loadHistory);
document.querySelectorAll('[data-period]').forEach(b=>b.onclick=()=>{historyPeriod=b.dataset.period;document.querySelectorAll('[data-period]').forEach(x=>x.classList.toggle('active',x===b));loadHistory()});
$('recordHistory').onchange=async e=>{try{await api('history/settings',{enabled:e.target.checked});await sync();await loadHistory();note(e.target.checked?'Recording enabled. Location updates require your device permission.':'Recording paused. Existing history remains until deleted or expired.')}catch(error){note(error.message);await sync()}};
$('deleteHistory').onclick=async()=>{if(!confirm('Permanently delete all your recorded locations? This cannot be undone.'))return;try{await api('history/delete',{});await sync();await loadHistory();note('Your recorded history was deleted.')}catch(error){note(error.message)}};
$('mapFit').onclick=()=>{fitHistory();drawHistory()};function zoomHistory(factor){const [x,y,w,h]=mapBox;const nw=Math.max(1,Math.min(1500,w*factor));mapBox=[x+(w-nw)/2,y+(h-nw*600/1000)/2,nw,nw*600/1000];drawHistory()}
$('mapZoomIn').onclick=()=>zoomHistory(.6);$('mapZoomOut').onclick=()=>zoomHistory(1/.6);
$('historyMap').onclick=e=>{if(e.target.dataset.point!==undefined){pauseJourney();const p=historyData.points[+e.target.dataset.point];$('historySummary').textContent=`${historyDemo||historyData?.simulatedName?'SIMULATED · ':''}${new Date(p.at*1000).toLocaleString()} · ${p.lat.toFixed(5)}°, ${p.lon.toFixed(5)}° · ${p.zone}`}};
$('historyMap').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();e.target.click()}else if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();mapBox[0]+=(e.key==='ArrowRight'?1:e.key==='ArrowLeft'?-1:0)*mapBox[2]/5;mapBox[1]+=(e.key==='ArrowDown'?1:e.key==='ArrowUp'?-1:0)*mapBox[3]/5;drawHistory()}};
let dragMap=null;$('historyMap').onpointerdown=e=>{dragMap={x:e.clientX,y:e.clientY,box:[...mapBox],point:e.target.dataset.point};$('historyMap').setPointerCapture(e.pointerId)};$('historyMap').onpointerup=e=>{if(!dragMap)return;if(Math.abs(e.clientX-dragMap.x)+Math.abs(e.clientY-dragMap.y)<4){if(dragMap.point!==undefined){const p=historyData.points[+dragMap.point];$('historySummary').textContent=`${historyDemo||historyData?.simulatedName?'SIMULATED · ':''}${new Date(p.at*1000).toLocaleString()} · ${p.lat.toFixed(5)}°, ${p.lon.toFixed(5)}° · ${p.zone}`}dragMap=null;return;}const width=$('historyMap').getBoundingClientRect().width;mapBox=[dragMap.box[0]-(e.clientX-dragMap.x)/width*dragMap.box[2],dragMap.box[1]-(e.clientY-dragMap.y)/width*dragMap.box[2],dragMap.box[2],dragMap.box[3]];dragMap=null;drawHistory()};drawHistory();

function showSampleHistory(){
 historyRequest++;const now=Date.now()/1000;const d=new Date();let start=now-Number(historyPeriod)*86400;if(historyPeriod==='6m'||historyPeriod==='1y'){const day=d.getUTCDate();d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()-(historyPeriod==='6m'?6:12));const last=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0)).getUTCDate();d.setUTCDate(Math.min(day,last));start=d.getTime()/1000}
 const itinerary=[{days:310,lat:37.7749,lon:-122.4194,zone:'America/Los_Angeles'},{days:110,lat:40.7128,lon:-74.006,zone:'America/New_York'},{days:22,lat:51.5074,lon:-.1278,zone:'Europe/London'},{days:3,lat:25.2048,lon:55.2708,zone:'Asia/Dubai'},{days:.6,lat:19.076,lon:72.8777,zone:'Asia/Kolkata'},{days:.2,lat:19.1,lon:72.9,zone:'Asia/Kolkata'}];
 const points=OrbitJourney.daily(itinerary.map((p,i)=>({...p,id:i,at:now-p.days*86400})).filter(p=>p.at>=start));historyData={points,total:points.length,sampled:false};fitHistory();drawHistory();$('sampleHistory').textContent='Back to recorded history';
}
$('sampleHistory').onclick=()=>{historyDemo=!historyDemo;if(historyDemo)showSampleHistory();else{$('sampleHistory').textContent='Preview a sample journey';loadHistory()}};

updateHistoryControls();

function renderClockOrder(){const clocks=widgetClocks();$('clockOrder').innerHTML=clocks.map(p=>`<div class="clockOrderRow" draggable="true" data-clock="${escape(p.id)}"><span class="dragHandle" aria-hidden="true">⠿</span><div><b>${escape(p.name)}</b><small>${p.sample?'Sample · ':''}${escape(p.zone.replaceAll('_',' '))}</small></div><span class="zoneDelta listDelta" data-delta-zone="${escape(p.zone)}">${OrbitClock.signedDifferenceAt(p.zone,zone())}</span><button class="removeClock" data-remove-clock="${escape(p.id)}" aria-label="Remove ${escape(p.name)}">×</button></div>`).join('')||'<p class="footnote">Add a time zone or friend to start your list.</p>'}
$('clockOrder').onclick=e=>{const button=e.target.closest('[data-remove-clock]');if(!button)return;const id=button.dataset.removeClock;if(id.startsWith('zone:'))widgetSettings.zones=widgetSettings.zones.filter(z=>'zone:'+z!==id);else if(id.startsWith('sample-'))widgetSettings.excludedSamples=[...new Set([...(widgetSettings.excludedSamples||[]),id])];else{if(widgetSettings.friends===null)widgetSettings.friends=(state?.friends||[]).map(f=>f.id);widgetSettings.friends=widgetSettings.friends.filter(x=>x!==id)}widgetSettings.order=(widgetSettings.order||[]).filter(x=>x!==id);saveWidget();renderWidgetSettings();note('Clock removed.')};
$('addFriendClock').onclick=()=>{const id=$('friendToAdd').value;if(!id)return;widgetSettings.friends=[...new Set([...(widgetSettings.friends||[]),id])];saveWidget();renderWidgetSettings()};
let draggedClock=null;$('clockOrder').ondragstart=e=>{const row=e.target.closest('[data-clock]');if(!row)return;draggedClock=row.dataset.clock;e.dataTransfer.setData('text/plain',draggedClock);e.dataTransfer.effectAllowed='move';row.classList.add('dragging')};$('clockOrder').ondragover=e=>{if(draggedClock){e.preventDefault();e.dataTransfer.dropEffect='move'}};$('clockOrder').ondrop=e=>{e.preventDefault();const row=e.target.closest('[data-clock]');if(!row||!draggedClock)return;const ids=widgetClocks().map(p=>p.id),from=ids.indexOf(draggedClock),to=ids.indexOf(row.dataset.clock);if(from<0||to<0)return;ids.splice(to,0,ids.splice(from,1)[0]);widgetSettings.order=ids;draggedClock=null;saveWidget();note('Clock order saved.')};$('clockOrder').ondragend=()=>{draggedClock=null;renderClockOrder()};renderClockOrder();

function sampleWidgetPeople(){return Object.entries(sampleTrips).filter(([id])=>!(widgetSettings.excludedSamples||[]).includes(id)).map(([id,trip])=>({id,name:trip.name,...trip.stops[(widgetSettings.demoStep||0)%trip.stops.length],sample:true,mode:'location',historyAllowed:true,locationUpdated:Date.now()/1000,updated:Date.now()/1000}))}
function displayPeople(){return [...(state?.friends||[]),...(widgetSettings.sample?sampleWidgetPeople():[])]}
function loadSamplePersonHistory(id){const trip=sampleTrips[id];if(!trip)return;const now=Date.now()/1000,step=widgetSettings.demoStep||0;let days=Number(historyPeriod);if(historyPeriod==='6m'||historyPeriod==='1y'){const end=new Date(),start=new Date(end),day=start.getDate();start.setDate(1);start.setMonth(start.getMonth()-(historyPeriod==='6m'?6:12));const last=new Date(start.getFullYear(),start.getMonth()+1,0).getDate();start.setDate(Math.min(day,last));days=Math.ceil((end-start)/86400000)}const reports=Array.from({length:days},(_,i)=>{const age=days-1-i;return {id:i,at:now-age*86400,...trip.stops[(Math.floor(i/5)+step)%trip.stops.length]}});reports[reports.length-1]={...reports.at(-1),...trip.stops[step%trip.stops.length]};const points=OrbitJourney.daily(reports);historyData={points,total:points.length,sampled:false,simulatedName:trip.name};fitHistory();drawHistory();$('historySummary').textContent='SIMULATED · '+trip.name+' · '+points.length+' daily stops · no real tracking records';}
function enableSampleTracking(){widgetSettings.sample=true;widgetSettings.excludedSamples=[];saveWidget();render();updateHistoryControls();note('Sample tracking enabled. All sample locations and trips are simulated.')}
function advanceSampleTrips(){if(!widgetSettings.sample)enableSampleTracking();widgetSettings.demoStep=(widgetSettings.demoStep||0)+1;saveWidget();render();updateHistoryControls();if(!$('history').hidden)loadHistory();note('Sample trips advanced. People, time zones, offsets, and widgets updated.')}
function analogFace(z){const p=Object.fromEntries(new Intl.DateTimeFormat('en-US',{timeZone:z,hour:'numeric',minute:'numeric',hourCycle:'h23'}).formatToParts(new Date()).map(p=>[p.type,p.value]));const hour=(Number(p.hour)%12)*30+Number(p.minute)*.5,minute=Number(p.minute)*6;return `<div class="analogDisplay"><svg class="analogFace" viewBox="0 0 100 100" role="img" aria-label="${escape(time(z))}"><circle class="clockDial" cx="50" cy="50" r="47"/>${Array.from({length:12},(_,i)=>`<line class="clockTick" x1="50" y1="7" x2="50" y2="${i%3===0?15:11}" transform="rotate(${i*30} 50 50)"/>`).join('')}<line class="hourHand" x1="50" y1="52" x2="50" y2="27" transform="rotate(${hour} 50 50)"/><line class="minuteHand" x1="50" y1="54" x2="50" y2="16" transform="rotate(${minute} 50 50)"/><circle class="clockPin" cx="50" cy="50" r="3"/></svg><small class="analogTime">${time(z)}</small></div>`}
function updateWidgetTimes(){document.querySelectorAll('[data-delta-zone]').forEach(el=>el.textContent=OrbitClock.signedDifferenceAt(el.dataset.deltaZone,zone()));const clocks=widgetClocks();document.querySelectorAll('.widgetRow .clockDisplay').forEach((el,i)=>{if(clocks[i]){el.parentElement.querySelector('.zoneDelta').textContent=OrbitClock.signedDifferenceAt(clocks[i].zone,zone());el.innerHTML=widgetSettings.style==='analog'?analogFace(clocks[i].zone):'<strong>'+time(clocks[i].zone)+'</strong>'}})}
$('clockStyle').onchange=e=>{widgetSettings.style=e.target.value;saveWidget()};$('samplePeople').onchange=e=>{widgetSettings.sample=e.target.checked;if(e.target.checked)widgetSettings.excludedSamples=[];saveWidget();render();note(e.target.checked?'Sample people preview enabled. No real connections were added.':'Showing your saved clocks.')};

$('enableSampleTracking').onclick=enableSampleTracking;$('dashboardSamplePeople').onclick=enableSampleTracking;$('advanceSampleTrip').onclick=advanceSampleTrips;$('dashboardAdvanceSample').onclick=advanceSampleTrips;

// Initialize only after history state and all event handlers are ready.
widgetSettings.sample=true;if(!widgetSettings.zones.length)widgetSettings.zones=['Asia/Kolkata','Europe/London','America/New_York'];render();

function stopSampleTracking(){widgetSettings.sample=false;historyDemo=false;saveWidget();render();loadHistory();note('Sample people hidden. Your real connections and clocks remain.')}
$('stopSamples').onclick=stopSampleTracking;$('dashboardStopSamples').onclick=stopSampleTracking;

$('inviteButton').disabled=true;$('emptyInvite').disabled=true;
