let dashboardHistory=null,dashboardHistoryError='',dashboardHistoryLoading=false;
function renderDashboard(){
 const clocks=widgetClocks(),friends=state?.friends||[],sharing=state?.sharing||[];
 $('dashboardMode').textContent=widgetSettings.sample?'Sample clocks preview':state?'Your live overview':'Local clocks';
 const stats=[['Tracked clocks',clocks.length],['Connected people',new Set([...friends.map(p=>p.id),...sharing.map(p=>p.id)]).size],['Sharing your location',sharing.filter(p=>p.mode==='location').length],['History recording',state?.historyEnabled?'On':'Off']];
 $('dashboardStats').innerHTML=stats.map(([label,value])=>`<div class="dashStat"><span>${label}</span><strong>${value}</strong></div>`).join('');
 $('dashboardClocks').innerHTML=clocks.map(p=>`<article class="dashClock"><div class="dashClockTop"><div class="avatar">${escape(p.name.slice(0,1))}</div><div><h3>${escape(p.name)}</h3><small>${p.sample?'Sample person':p.standalone?'Standalone time zone':'Friend'} · ${escape(p.zone.split('/').pop().replaceAll('_',' '))}</small></div></div><div class="dashClockTime" data-dashboard-clock="${escape(p.zone)}">${widgetSettings.style==='analog'?analogFace(p.zone):'<strong>'+time(p.zone)+'</strong>'}</div><div class="dashClockBottom"><span class="zoneDelta" data-dashboard-delta="${escape(p.zone)}">${OrbitClock.signedDifferenceAt(p.zone,zone())}</span><small>${new Intl.DateTimeFormat(undefined,{timeZone:p.zone,weekday:'short',month:'short',day:'numeric'}).format(new Date())}</small></div>${!p.sample&&!p.standalone?`<div class="dashFreshness">${age(p.updated)}</div>`:''}${p.mode==='location'&&p.lat!=null?`<a class="location" target="_blank" rel="noopener" href="https://maps.apple.com/?ll=${p.lat},${p.lon}">View shared location ↗</a>`:''}</article>`).join('')||'<div class="dashEmpty">Add a time zone or invite a friend to start your dashboard.</div>';
 const connected=[...new Map([...friends,...sharing].map(p=>[p.id,p])).values()];
 $('dashboardSharing').innerHTML=connected.map(p=>{const outgoing=sharing.find(f=>f.id===p.id),incoming=friends.find(f=>f.id===p.id);return `<div class="dashConnection"><b>${escape(p.name)}</b><small>You share: ${outgoing?.mode==='location'?'location':outgoing?.mode==='zone'?'time zone':'off'}${outgoing?.history_shared?' + history':''}</small><small>They share: ${incoming?.mode==='location'?'location':incoming?'time zone':'off'}${incoming?.historyAllowed?' + history':''}</small></div>`}).join('')||'<p class="footnote">No real connections yet. Sample clocks are only a preview.</p>';
 $('dashboardWidgetInfo').innerHTML=`<div class="dashSetting"><span>Widget style</span><b>${widgetSettings.style==='analog'?'Analog':'Digital'}</b></div><div class="dashSetting"><span>Widget size</span><b>${escape(widgetSettings.size[0].toUpperCase()+widgetSettings.size.slice(1))}</b></div><div class="dashSetting"><span>Personal history</span><b>${state?.historyEnabled?'Recording':'Paused'}</b></div><p class="footnote">Location updates arrive while the app is open. Each person controls what they share.</p>`;
 renderDashboardMap();
}
function renderDashboardMap(){
 const points=dashboardHistory?.points||[];let routes='';for(let i=1;i<points.length;i++)routes+=OrbitJourney.segment(points[i-1],points[i]).map(pair=>`<path class="journeyLine" d="M${pair[0].join(' ')} L${pair[1].join(' ')}"/>`).join('');
 $('dashboardMap').innerHTML='<rect width="1000" height="600" fill="var(--ocean-edge)"/>'+worldPaths+routes+points.map(p=>{const [x,y]=project(p.lon,p.lat);return `<circle cx="${x}" cy="${y}" r="5" class="historyDot visited"/>`}).join('');
 $('dashboardHistorySummary').textContent=dashboardHistoryError?dashboardHistoryError:!token?'Open History to explore a clearly labeled sample journey.':dashboardHistoryLoading?'Loading your recorded history…':points.length?`${points.length} recorded days · last recorded ${new Date(points.at(-1).at*1000).toLocaleString()}`:state?.historyEnabled?'Recording is on. Your first location update will appear here.':'Recording is paused. Enable it in History to start your private journey.';
}
async function refreshDashboardHistory(){if(!token||dashboardHistoryLoading)return;dashboardHistoryLoading=true;renderDashboardMap();try{dashboardHistory=await api('history?period=30&granularity=day');dashboardHistoryError=''}catch(e){dashboardHistoryError='History unavailable · '+e.message}finally{dashboardHistoryLoading=false;renderDashboardMap()}}
function tickDashboard(){document.querySelectorAll('[data-dashboard-clock]').forEach(el=>el.innerHTML=widgetSettings.style==='analog'?analogFace(el.dataset.dashboardClock):'<strong>'+time(el.dataset.dashboardClock)+'</strong>');document.querySelectorAll('[data-dashboard-delta]').forEach(el=>el.textContent=OrbitClock.signedDifferenceAt(el.dataset.dashboardDelta,zone()))}
document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>document.querySelector(`[data-tab="${b.dataset.open}"]`).click());renderDashboard();if(token)refreshDashboardHistory();
